---
#roles:
#  - name: clickhouse
#    git:
#      repo: git@github.com:AlexeySetevoi/ansible-clickhouse.git
#      version: master
#
#  - name: vector
#    git:
#      repo: git@github.com:Alexandr-Vedernikov/vector-role.git
#      version: master
#
#  - name: lighthouse
#    git:
#      repo: git@github.com:Alexandr-Vedernikov/lighthouse-role.git
#      version: master
#
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13.0"
    name: clickhouse
  - src: git@github.com:Alexandr-Vedernikov/lighthouse-role.git
    scm: git
    version: "0.2"
    name: lighthouse-role
  - src: git@github.com:Alexandr-Vedernikov/vector-role.git
    scm: git
    version: "0.2"
    name: vector-role