version: "3"
services:
  postgres:
    image: postgres:12.14
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test-admin-user"
      POSTGRES_PASSWORD: "Password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      #- ./script. Init Database:/docker-entrypoint-initdb.d
      - ./bd1:/var/lib/postgresql/data
      - ./backup:/var/lib/postgresql/backup
    ports:
      - "5432:5432"
    restart: unless-stopped
