ISO = "bento/ubuntu-20.04"
#NET = "192.168.1."
#DOMAIN =""
DOMAIN = ".Workgroup"
HOST_PREFIX = "TestServer"
INVENTORY_PATH = "./inventory"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

servers = [
  {
    :hostname => HOST_PREFIX + "1",
    :ssh_host => "20000",
    :ssh_vm => "22",
    :ram => 2048,
    :core => 2
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine [:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine [:hostname] + DOMAIN
      node.vm.network "public_network", bridge: "wlo1"
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine [:hostname]
      end
      node.vm.provision "ansible" do |setup|
	    setup.inventory_path = INVENTORY_PATH
	    setup.playbook = "./playbook.yml"
	    setup.become = true
	    setup.extra_vars = { ansible_user: 'vagrant' }
      end
    end
  end
end