# -*- mode: ruby -*-
# vi: set ft=ruby :

$clickhouse_name = "clickhouse"
$clickhouse_ip = "192.168.1.200"
$vector_name = "vector"
$vector_ip = "192.168.1.201"
$iso = "./centos7.box"

Vagrant.configure("2") do |config|
  config.vm.define $clickhouse_name do |config|
  config.vm.network "public_network", bridge: "wlo1", ip: $clickhouse_ip
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "4096"
    end
    config.vm.box = $iso
    config.vm.hostname = $clickhouse_name

    config.vm.provision "shell", inline: <<-SHELL
      yum install -y python3
    SHELL

    end
  end

Vagrant.configure("2") do |config|
  config.vm.define $vector_name do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "4096"
    end
    config.vm.box = $iso
    config.vm.hostname = $vector_name
    config.vm.network "public_network", bridge: "wlo1", ip: $vector_ip

    config.vm.provision "shell", inline: <<-SHELL
      yum install -y python3
    SHELL

    end
  end