---
  servers:
    hosts:
      clickhouse:
        ansible_host: 192.168.1.200
        ansible_ssh_private_key_file: ./.vagrant/machines/clickhouse/virtualbox/private_key
      vector:
        ansible_host: 192.168.1.201
        ansible_ssh_private_key_file: ./.vagrant/machines/vector/virtualbox/private_key